#include <rose/registers.h>

/* we have to define this stuff ourselves so that we don't get conflicting
 * type/other definitions */
extern char *strdup(const char *);
extern void free(void *);
extern int printf(const char *, ...);

#ifdef __x86_64__
#  error "64-bit builds are not yet supported"
#endif

#define offsetof(type, field)\
    ((size_t) (&(((type *) 0x0)->field)))

#define write_macro(type, field)\
    _write_macro(#type, #field, offsetof(struct type, field))

static void
upper_case_str(char *s)
{
    while(*s) {
        *s = toupper(*s);
        s++;
    }
}

static void
_write_macro(char *type_name, char *field_name, size_t offset)
{
    type_name  = strdup(type_name);
    field_name = strdup(field_name);

    upper_case_str(type_name);
    upper_case_str(field_name);

    printf("%%define STRUCT_%s_%s_OFFSET 0x%08x\n", type_name, field_name, offset);

    free(type_name);
    free(field_name);
}

int
main(int argc, char **argv)
{
    printf("; This file is generated by %s\n\n", argv[0]);

    write_macro(registers, edi);
    write_macro(registers, esi);
    write_macro(registers, ebp);
    write_macro(registers, esp);
    write_macro(registers, ebx);
    write_macro(registers, edx);
    write_macro(registers, ecx);
    write_macro(registers, eax);

    return 0;
}
